name = "Coluna documentation"

[deps]
BlockDecomposition = "6cde8614-403a-11e9-12f1-c10d0f0caca0"
Coluna = "88b4ec78-b192-11e8-04aa-4d367dd96a64"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterMermaid = "a078cd44-4d9c-4618-b545-3ab9d77f9177"
GLPK = "60bf3e95-4087-53dc-ae20-288a0d20c6a6"
HiGHS = "87dc4568-4c63-4d18-b0c0-bb2238e4078b"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MathOptInterface = "b8f27783-ece8-5eb3-8dc8-9495eed66fee"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"

[compat]
BlockDecomposition = "1.6"
MathOptInterface = "1.0"
